# Site Settings
title: My Blog
description: A short description of what your blog is about.
url: 'https://sarastro.ng'
baseurl: ''

# Author
author:
  name: Sara Strong
  email: you@example.com

# Theme
theme: minima

# Build Settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
